from appium.webdriver.common.appiumby import AppiumBy as Aby


class RECEIVERACT:
    actions1 = [
        ('click', 'id', 'el', Aby.ID, '1'),
        ('click', 'xpath', 'el', Aby.XPATH, '2'),
        ('click', 'xpath', 'el', Aby.XPATH, '3'),
        ('click', 'xpath', 'el', Aby.XPATH, '4'),
        # ('rolling', 'xpath', 'xpath', 'el', Aby.XPATH, '5', '6'),
        # ('click', 'xpath', 'el', Aby.XPATH, '7'),
        # ('click', 'xpath', 'el', Aby.XPATH, '8'),
        # ('rolling', 'xpath', 'xpath', 'el', Aby.XPATH, '9', '10'),
        # ('click', 'xpath', 'el', Aby.XPATH, '11'),
        # ('click', 'xpath', 'el', Aby.XPATH, '12'),
        # ('click', 'xpath', 'el', Aby.XPATH, '13'),
        # ('click', 'xpath', 'el', Aby.XPATH, '14'),
        # ('click', 'xpath', 'el', Aby.XPATH, '15'),
        # ('click', 'xpath', 'el', Aby.XPATH, '16'),
        # ('click', 'xpath', 'el', Aby.XPATH, '17'),
        # ('click', 'xpath', 'el', Aby.XPATH, '18'),
        # ('click', 'xpath', 'el', Aby.XPATH, '19'),
        # ('click', 'xpath', 'el', Aby.XPATH, '20'),
        # ('click', 'xpath', 'el', Aby.XPATH, '21'),
        # ('click', 'xpath', 'el', Aby.XPATH, '22'),
        # ('click', 'xpath', 'el', Aby.XPATH, '23'),
        # ('click', 'xpath', 'el', Aby.XPATH, '24'),
        # ('click', 'xpath', 'el', Aby.XPATH, '25'),
        # ('click', 'xpath', 'el', Aby.XPATH, '26'),
        # ('click', 'xpath', 'el', Aby.XPATH, '27'),
        # ('click', 'xpath', 'el', Aby.XPATH, '28'),
        # ('click', 'xpath', 'el', Aby.XPATH, '29'),
        # ('click', 'xpath', 'el', Aby.XPATH, '30'),
        # ('click', 'xpath', 'el', Aby.XPATH, '31'),
        # ('click', 'xpath', 'el', Aby.XPATH, '32'),
        # ('click', 'xpath', 'el', Aby.XPATH, '33'),
        # ('click', 'xpath', 'el', Aby.XPATH, '34'),
        # ('click', 'xpath', 'el', Aby.XPATH, '35'),
        # ('click', 'xpath', 'el', Aby.XPATH, '36'),
        # ('click', 'xpath', 'el', Aby.XPATH, '37'),
        # ('click', 'xpath', 'el', Aby.XPATH, '38'),
        # ('click', 'xpath', 'el', Aby.XPATH, '39'),
        # ('click', 'xpath', 'el', Aby.XPATH, '40'),
        # ('click', 'xpath', 'el', Aby.XPATH, '41'),
        # ('click', 'xpath', 'el', Aby.XPATH, '42'),
        # ('click', 'xpath', 'el', Aby.XPATH, '43'),
        # ('click', 'xpath', 'el', Aby.XPATH, '44'),
        # ('click', 'xpath', 'el', Aby.XPATH, '45'),
        # ('click', 'xpath', 'el', Aby.XPATH, '46'),
        # ('click', 'xpath', 'el', Aby.XPATH, '47'),
        # ('click', 'xpath', 'el', Aby.XPATH, '48'),
        # ('click', 'xpath', 'el', Aby.XPATH, '49'),
        #
        # ('rolling', 'xpath', 'xpath', 'el', Aby.XPATH, '50', '51'),
        # ('click', 'xpath', 'el', Aby.XPATH, '52'),
        # ('click', 'xpath', 'el', Aby.XPATH, '53'),
        # ('click', 'xpath', 'el', Aby.XPATH, '54'),
        # ('click', 'xpath', 'el', Aby.XPATH, '55'),
        # ('click', 'xpath', 'el', Aby.XPATH, '56'),
        ('time', 3)
    ]

    actions2 = [
        ('click', 'id', 'el', Aby.ID, '1'),
        ('click', 'xpath', 'el', Aby.XPATH, '2'),
        ('click', 'xpath', 'el', Aby.XPATH, '3'),
        ('rolling', 'xpath', 'xpath', 'el', Aby.XPATH, '4', '5'),
        # ('click', 'xpath', 'el', Aby.XPATH, '6'),
        # ('click', 'xpath', 'el', Aby.XPATH, '7'),
        ('click', 'xpath', 'el', Aby.XPATH, '8'),
        ('click', 'xpath', 'el', Aby.XPATH, '9'),
        ('click', 'xpath', 'el', Aby.XPATH, '10'),
        ('click', 'xpath', 'el', Aby.XPATH, '11'),
        ('click', 'xpath', 'el', Aby.XPATH, '12'),
        ('click', 'xpath', 'el', Aby.XPATH, '13'),
        ('click', 'xpath', 'el', Aby.XPATH, '14'),
        ('click', 'xpath', 'el', Aby.XPATH, '15'),
        ('click', 'xpath', 'el', Aby.XPATH, '16'),
        ('click', 'xpath', 'el', Aby.XPATH, '17'),
        ('click', 'xpath', 'el', Aby.XPATH, '18'),
        ('click', 'xpath', 'el', Aby.XPATH, '19'),
        ('click', 'xpath', 'el', Aby.XPATH, '20'),
        ('click', 'xpath', 'el', Aby.XPATH, '21'),
        ('click', 'xpath', 'el', Aby.XPATH, '22'),
        ('click', 'xpath', 'el', Aby.XPATH, '23'),
        ('click', 'xpath', 'el', Aby.XPATH, '24'),
        ('click', 'xpath', 'el', Aby.XPATH, '25'),
        ('click', 'xpath', 'el', Aby.XPATH, '26'),
        ('click', 'xpath', 'el', Aby.XPATH, '27'),
        ('click', 'xpath', 'el', Aby.XPATH, '28'),
        ('click', 'xpath', 'el', Aby.XPATH, '29'),
        ('click', 'xpath', 'el', Aby.XPATH, '30'),
        ('click', 'xpath', 'el', Aby.XPATH, '31'),
        ('click', 'xpath', 'el', Aby.XPATH, '32'),
        ('click', 'xpath', 'el', Aby.XPATH, '33'),
        ('click', 'xpath', 'el', Aby.XPATH, '34'),
        ('click', 'xpath', 'el', Aby.XPATH, '35'),
        ('click', 'xpath', 'el', Aby.XPATH, '36'),
        ('click', 'xpath', 'el', Aby.XPATH, '37'),
        ('click', 'xpath', 'el', Aby.XPATH, '38'),
        ('click', 'xpath', 'el', Aby.XPATH, '39'),
        ('click', 'xpath', 'el', Aby.XPATH, '40'),
        ('click', 'xpath', 'el', Aby.XPATH, '41'),
        ('click', 'xpath', 'el', Aby.XPATH, '42'),
        ('click', 'xpath', 'el', Aby.XPATH, '43'),
        ('click', 'xpath', 'el', Aby.XPATH, '44'),
        ('click', 'xpath', 'el', Aby.XPATH, '45'),
        ('click', 'xpath', 'el', Aby.XPATH, '46'),
        ('click', 'xpath', 'el', Aby.XPATH, '47'),
        ('click', 'xpath', 'el', Aby.XPATH, '48'),
        ('rolling', 'xpath', 'xpath', 'el', Aby.XPATH, '49', '50'),
        ('click', 'xpath', 'el', Aby.XPATH, '51'),
        ('click', 'xpath', 'el', Aby.XPATH, '52'),
        ('click', 'xpath', 'el', Aby.XPATH, '53'),
        ('click', 'xpath', 'el', Aby.XPATH, '54'),
        ('click', 'xpath', 'el', Aby.XPATH, '55'),
        ('click', 'xpath', 'el', Aby.XPATH, '56'),
        ('click', 'xpath', 'el', Aby.XPATH, '57'),
        ('click', 'xpath', 'el', Aby.XPATH, '58'),
        ('click', 'xpath', 'el', Aby.XPATH, '59'),
        ('click', 'xpath', 'el', Aby.XPATH, '60'),
        ('click', 'xpath', 'el', Aby.XPATH, '61'),

        ('time', 3)
    ]

